### ISSUE TITLE
WriteRest OP out of range

### ISSUE THREAD

**Issue by fr500** [libretro/libretro-ppsspp#22]
@ToadKing PPSSPP recently merged your PR, and now I'm getting this:
https://www.dropbox.com/s/cnjjtm43hkzobxj/Screenshot%202014-10-18%2013.08.54.png?dl=0

Not sure if your workaround was swallowed by recent changes or what

https://github.com/hrydgard/ppsspp/pull/6694
https://github.com/hrydgard/ppsspp/issues/1106

**Comment by Awakened0** [comment]
I'm getting this on Falcom games (Ys VII, Nayuta, Gurumin) in the latest (6-7-15) Win64 build of the core.

**Comment by fr500** [comment]
same for disgaea 2

**Comment by ToadKing** [comment]
I've tracked down the issue to Jit::RestoreRoundingMode. It tries to move a value to mips_->temp which is in high memory. However, fixing the executable memory allocator to return values in high memory causes another issue in Jit::UpdateRoundingMode, where js.hasSetRounding is in low memory but is still trying to be used by the JIT. I am unsure how this should be solved since I don't know very much about how the JIT works for PPSSPP.

**Comment by ghenry22** [comment]
still see this same error launching any game with the PPSSPP core, aside from the error the emulator works perfectly.  Would it be possible to suppress the error if it cannot be fixed easily so at least the user experience doesn't result in annoying pop ups.

**Comment by tulu** [comment]
As ghenry22, it still persists the same error with the core updated from RetroArch 1.3 released a month ago. Are there any news regarding the fix?

**Comment by brandleesee** [comment]
Happens also to Dissidia.
Final Fantasy Tactics works well.
Of course, it is first necessary to bypass the PPSSPP --> assets --> ppge_atlas.zim

**Comment by emko** [comment]
any way to prevent the error from showing?

**Comment by brandleesee** [comment]
Funnily enough, I still cannot play Dissidia on RetroArch [PC].
But, trying it in Lakka Live USB on the same hardware, no error whatsoever!

**Comment by hs5tb** [comment]
It stills happens in Windows 7 64 bits, game "Dante's Inferno (USA)". I just see the popup, click "ok" then the game starts ok. Any news about that?

**Comment by eobet** [comment]
Just waving the flag that I too have this issue.

Unless I'm mistaken, the solution which caused this issue to be closed is a compiler flag? I have no means of compiling this myself, but it seems to be still present more than a year after being closed.

I just downloaded and did a fresh install on a new Windows 10 64-bit machine.

**Comment by TehKAMI** [comment]
I'm getting this specific error in these games:

- Dante's Inferno (runs after clicking "yes", but the screen flickers, in-game smoke/dust is rainbow colored and several special effects are missing | crashes upon choosing "no")
- Dissidia 012: Duodecim Final Fantasy (crashes whichever option I choose)
- God of War: Ghost of Sparta (runs after clicking "yes", but the seems unstable while playing with frequent random FPS drops | crashes upon choosing "no")

![psperror](https://cloud.githubusercontent.com/assets/21988479/18232613/6c4252da-72d3-11e6-8bd2-a7e91ba458a5.PNG)

**Comment by mgabrel** [comment]
Getting this error when trying to run Metal Gear Solid: Peace Walker (USA) (crashes after choosing either option):

![peace-walker-error](https://cloud.githubusercontent.com/assets/2373142/18849811/5415e20c-83fa-11e6-98ed-3872dc331c7b.PNG)

**Comment by ShadwDrgn** [comment]
I have this problem as well with the appropriate files in the system folder for PPSSPP. This used to work great on my linux libretro stuff. on ubuntu but after migrating to windows 10 this has started happening. Same error as mgabrel except with different addresses.

**Comment by Denus01** [comment]
I have this issue with Outrun 2006 Coast 2 Coast and Monster Hunter Freedom.
Then, I get the error message that Retroarch has stopped working.

I've tried several versions of the games (Eur, US etc) but the problem remains.

**Comment by ScottGotRekt** [comment]
A lot of games I'm attempting to play come up with this error.

GTA - Vice City Stories
Metal Gear ACID (1 & 2)
Metal Gear Solid - Peace Walker

just to name a few...

Please fix this ASAP!

**Comment by Demeth** [comment]
Same problem.

**Comment by marty606** [comment]
add me to the list, I have been waiting years for this core to functions without errors.

**Comment by twinaphex** [comment]
No need to have this open when there will be a rebase, and more nagging about it is not what I need right now.

**Comment by brandleesee** [comment]
While we wait for your rebasing, changing CPU Core to interpreter does not trigger the WriteRest dialog. Tested only for Dissidia. I only fiddled with that setting after observing the closed and still open issues on original PPSSPP github account in relation to WriteRest query.
